config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'about', to: 'pages#about'

  get 'signup', to: 'accounts#signup'
  post 'signup', to: 'accounts#create'

  delete "logout", to: 'accounts#destroy' 

  get 'login', to: 'accounts#login'
  post 'login', to: 'accounts#getaccess'

  get 'changepass', to: 'accounts#changepass'

  get 'dashboard', to: 'dashboard#dashboard'

  get 'account', to: 'dashboard#account'

  get 'billing', to: 'dashboard#billing'

  get 'shipping', to: 'dashboard#shipping'
  post 'shipping', to: 'dashboard#createshipping'

  get 'orders', to: 'dashboard#orders'

  get 'wishlist', to: 'dashboard#wishlist'
  
  get 'books', to: 'products#books'

  get 'percussion', to: 'products#percussion'
  
  get 'pianos', to: 'products#pianos'

  get 'stringed', to: 'products#stringed'

  get 'wind', to: 'products#wind'

  resources :categories do
    resources :products, only: [:index]
  end

end

app/models/address.rb
class Address < ApplicationRecord
    validates :street_number, presence: true
    validates :street_address, presence: true
    validates :city, presence: true
    validates :province, presence: true
    validates :area_code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord

    has_many :products

    validates :product_name, presence: true
    validates :product_price, presence: true

end

app/models/user.rb
class User < ApplicationRecord

    has_one :address
    
    has_secure_password

    validates :email, presence: true, uniqueness: true
    
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

    def signup
        @user = User.new
    end

    def create
        @user =  User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to dashboard_path, notice: "Account Successfully Created"
        else
            render :signup, status: 422
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out Successfully"
    end


    def login

    end

    def getaccess

        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to dashboard_path, notice: "Logged In Successfully"
        else
            flash[:alert] = "Invalid email or password"
            puts "Invalid details"
            render :login, status: 422
        end

    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

    before_action :user_session

    def dashboard
        
    end

    def account
    
    end

    def billing
    
    end

    def orders
    

    end

    def shipping
  
    end

    def createshipping
        @address = Address.new(shippingparams)
        if @address.save
            redirect_to dashboard_path, notice: "Account Successfully Created"
        else
            render :account, status: 422
        end
    end


    def wishlist
  

    end

    private

    def user_session
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
        end
    end


    def shippingparams
        params.permit(:street_number, :street_address, :city, :area_code, :province, :user_id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
        end
    end

    def about
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def stringed
        @category = Category.find_by(name: "Strings")
        @products = @category.products
    end
    
    def books
        @category = Category.find_by(name: "Books")
        @products = @category.products
    end

    def percussion
        @category = Category.find_by(name: "Percussion")
        @products = @category.products
    end

    def wind
        @category = Category.find_by(name: "Wind")
        @products = @category.products
    end

    def pianos
        @category = Category.find_by(name: "Pianos")
        @products = @category.products
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/login.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
    <div class="position-absolute top-50 start-50 translate-middle">
        <h1> Welcome back to Zen Music! </h1>
        <p> 
            Your musical journey continues here. Log in to your account to access your personalized recommendations, track your orders, and explore our extensive catalog with ease. Your passion for music deserves an experience that's harmonious and hassle-free. Let's make beautiful music together – log in now and pick up where you left off
        </p>

            <%= form_with url: login_path do |form|%>
                <div class="mb-3">
                    <%= form.label :email, class:"form-label"%>
                    <%= form.text_field :email, class:"form-control"%>
                </div>
                <div class="mb-3">
                    <%= form.label :password, class:"form-label"%>
                    <%= form.password_field :password, class:"form-control"%>
                </div>
                <div class="mb-3">
                    <%= form.submit "Login", class: "btn btn-info"%>
                </div>
            <%end%>
    </div>

</div>

app/views/accounts/signup.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
    <div class="position-absolute top-50 start-50 translate-middle">
    <h1> Ready to embark on a musical journey like no other? </h1>
    <p> 
        Join the Zen Music community today! Sign up to receive exclusive updates, special offers, and musical inspiration straight to your inbox. Whether you're a seasoned musician or just beginning your melodic adventure, our newsletter is your ticket to stay in tune with the latest arrivals, expert tips, and exciting events. Don't miss out – let's create music together!
    </p>
        <%= form_with model: @user, url: signup_path do |form| %>
            <% if @user.errors.any?%>
                    <div class="alert alert-danger">
                        <% @user.errors.full_messages.each do |message| %>
                            <div>
                                <%= message%>
                            </div>
                        <%end%>
                    </div>
                <%end%>
            <div class="mb-3">
                <%= form.label :email, class:"form-label"%>
                <%= form.text_field :email, class:"form-control"%>
            </div>
            <div class="mb-3">
                <%= form.label :password, class:"form-label"%>
                <%= form.password_field :password, class:""%>
                <%= form.label :password_confirmation, class:"form-label"%>
                <%= form.password_field :password_confirmation, class:""%>
            </div>
            <div class="mb-3">
                <%= form.submit "Sign Up", class: "btn btn-info"%>
            </div>
        <%end%>
    </div>
</div>

app/views/dashboard/account.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
<%= render 'layouts/tabs' %>
    <% if @user%>
        <table class="table table-striped">
            <h4 class="mt-4">Personal Details</h4>
            <tbody>
                <tr>
                    <td>FIRST NAME</td>
                    <td> ADDING FUNTIONALITY LATER </td>
                </tr>
                <tr>
                    <td>SURNAME NAME</td>
                    <td> ADDING FUNTIONALITY LATER </td>
                </tr>
                <tr>
                    <td>EMAIL ADDRESS</td>
                    <td><%=@user.email%></td>
                </tr>
                <tr>
                    <td>CONTACT NUMBER</td>
                    <td> ADDING FUNTIONALITY LATER </td>
                </tr>
            </tbody>
        </table>
    <% else %>
        
    <% end %>
        <div class="d-flex justify-content-around">
            <%= button_to "Edit Personal Details", changepass_path, class:"btn btn-info"%>
            <%= button_to "Change Password", changepass_path, class:"btn btn-info"%>
        </div>
</div>

app/views/dashboard/billing.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
<%= render 'layouts/tabs' %>

     <% if @user%>
            <table class="table table-striped">
                <h4 class="mt-4">Billing Details</h4>
                <tbody>
                    <tr>
                        <td>Bank Name</td>
                        <td> ADDING FUNTIONALITY LATER </td>
                    </tr>
                    <tr>
                        <td>Account Number</td>
                        <td> ADDING FUNTIONALITY LATER </td>
                    </tr>
                    <tr>
                        <td>Branch Name</td>
                        <td><%=@user.email%></td>
                    </tr>
                    <tr>
                        <td>Branch</td>
                        <td> ADDING FUNTIONALITY LATER </td>
                    </tr>
                </tbody>
            </table>
       <% else %>
            <h1>Something went horribly wrong somewhere</h1>
       <% end %>
    <%= button_to "Change Billing Details", changepass_path, class:"btn btn-info"%>
</div>

app/views/dashboard/dashboard.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">

    <%= render 'layouts/tabs' %> 

    <% if @user%>
        <div class="container-sm">
            <div>
                <p> Logged in as <%= @user.email%> </p>
                <br/>
                <%= button_to "Logout", logout_path, method: :delete %>
            </div>
        </div>
    <%end%>

</div>

app/views/dashboard/orders.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
<%= render 'layouts/tabs' %>

<div>
<h1>View orders</h1>
</div>
    <h2>Under Construction</h2>

</div>

app/views/dashboard/shipping.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
<%= render 'layouts/tabs' %>

        <div class="container">
            <h4 class="mt-4">Shipping Address</h4>
            <% if @user.address.present? %>
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td>Street Address</td>
                            <td> <%= @user.address.street_number.to_s + " " + @user.address.street_address%> </td>
                        </tr>
                        <tr>
                            <td>Neighbourhood</td>
                            <td> <%= @user.address.neighbourhood %> </td>
                        </tr>
                        <tr>
                            <td>City</td>
                            <td> <%= @user.address.city %> </td>
                        </tr>
                        <tr>
                            <td>Area Code</td>
                            <td> <%= @user.address.area_code %> </td>
                        </tr>
                        <tr>
                            <td>Province</td>
                            <td> <%= @user.address.province %> </td>
                        </tr>
                    </tbody>
                </table>
            <% else %>
                <%= form_with model: @address, url: shipping_path do |form| %>
                    <div class="mb-3">
                        <%= form.label :street_number, class:"form-label"%>
                        <%= form.text_field :street_number, class:"form-control"%>
                        <%= form.label :street_address, class:"form-label"%>
                        <%= form.text_field :street_address, class:"form-control"%>
                        <%= form.label :neighbourhood, class:"form-label"%>
                        <%= form.text_field :neighbourhood, class:"form-control"%>
                        <%= form.label :city, class:"form-label"%>
                        <%= form.text_field :city, class:"form-control"%>
                        <%= form.label :area_code, class:"form-label"%>
                        <%= form.text_field :area_code, class:"form-control"%>
                        <%= form.label :province, class:"form-label"%>
                        <%= form.text_field :province, class:"form-control"%>
                        <% form.text_field :street_address, class:"form-control"%>
                        <%= form.hidden_field :user_id, value: @user.id %>
                    </div>
                    <div class="mb-3">
                        <%= form.submit "Add Address", class: "btn btn-info"%>
                    </div>
                <%end%>
            <% end %>
            <%= button_to "Change Shipping Details", changepass_path, class:"btn btn-info"%>
        </div>
</div>

app/views/dashboard/wishlist.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
<%= render 'layouts/tabs' %>

<div>
<h1>Wishlist</h1>
</div>
<h2>Under Construction</h2>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid d-flex justify-content-evenly">
    <a class="navbar-brand" href="/">Zen Music</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ">
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Music Books", books_path, class:"nav-link" %> </li>
            <li><%= link_to "Percussion Instruments", percussion_path, class:"nav-link " %> </li>
            <li><%= link_to "Pianos and Keyboards", pianos_path, class:"nav-link" %> </li>
            <li><%= link_to "String Instruments", stringed_path, class:"nav-link" %> </li>
            <li><%= link_to "Wind Instruments", wind_path, class:"nav-link" %> </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Help Center</a>
        </li>
         <li class="nav-item">
          <%= link_to "Login", login_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", signup_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>


            

app/views/layouts/_sidenav.html.erb
<nav id="sidebarMenu" class=" d-lg-block sidebar">
    <div class="position-sticky">
        <h6 class="mx-2 mt-2"> Product Categories</h6>
        <div class="list-group list-group-flush mx-3 mt-3 mb-3">
            <%= link_to "Music Books", books_path, class:"nav-link" %>
            <%= link_to "Percussion Instruments", percussion_path, class:"nav-link " %>
            <%= link_to "Pianos and Keyboards", pianos_path, class:"nav-link" %>
            <%= link_to "String Instruments", stringed_path, class:"nav-link" %>
            <%= link_to "Wind Instruments", wind_path, class:"nav-link" %>
        </div>
    </div>
</nav>

app/views/layouts/_tabs.html.erb
<div class="tabs">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <%= link_to "Account Settings", account_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Billing Details", billing_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Shipping Details", shipping_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Orders", orders_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Wishlist", wishlist_path, class:"nav-link" %>
        </li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zen Music</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# BOOTSTRAP %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
 <%= render 'layouts/nav' %> 

 <div class="container c-body">
 </div>

app/views/pages/index.html.erb
 <%= render 'layouts/nav' %> 

<div class="container">

<div class="px-4 py-5 my-5 text-center">
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <div class="hero-text">
            <h2 class="display-5 fw-bold text-body-emphasis">Harmony Found, Music Unleashed</h2>
                    <p class="lead mb-4">Welcome to Zen Music, your harmonious haven for all things musical. Immerse yourself in a world of instruments that resonate with your soul. Whether you're a budding musician, a seasoned maestro, or simply a music enthusiast, our extensive collection caters to every musical passion. From the soothing strums of acoustic guitars to the electrifying beats of drum kits, we offer a symphony of choices. Discover your musical Zen at our store today and let your creativity sing.</p>
        </div>
            <%= image_tag("hero_image.png", width:"35%") %>
    </div>

</div>

<div class="services d-flex justify-content-evenly">
    <div class="card" style="width: 18rem;">
        <%= image_tag("guitar_category_image.png") %>
        <div class="card-body">
            <h5 class="card-title">String Instruments</h5>
            <p class="card-text">Experience the timeless elegance and versatility of stringed instruments at Zen Music. From the warm, soul-stirring tones of acoustic guitars to the electrifying sounds of electric guitars and the melodic charm of violins, our collection caters to every string enthusiast. Unleash your inner musician with instruments that resonate with your passion.</p>
            <%= link_to "Shop String Instruments", stringed_path, class:"btn btn-dark" %>
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <%= image_tag("drums_category_image.png") %>
        <div class="card-body">
            <h5 class="card-title">Percussion Instruments</h5>
            <p class="card-text">Feel the rhythm and let your creativity flow with our percussion instruments. Whether you're drawn to the primal beats of drums, the intricate patterns of hand percussion, or the shimmering sounds of cymbals, our percussion collection offers a world of possibilities. Explore the heartbeat of music at Zen Music.</p>
            <%= link_to "Shop Percussion Instruments", percussion_path, class:"btn btn-dark" %>
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <%= image_tag("saxophone_category_image.png") %>
        <div class="card-body">
            <h5 class="card-title">Wind Instruments</h5>
            <p class="card-text">Explore the world of wind instruments and let your music take flight. At Zen Music, we offer a wide range of wind instruments, from the enchanting melodies of flutes and saxophones to the bold and brassy sounds of trumpets and trombones. Elevate your musical journey with the perfect wind instrument for your unique style.</p>
            <%= link_to "Shop Wind Instruments", wind_path, class:"btn btn-dark" %>
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <%= image_tag("piano_category_image.png") %>
        <div class="card-body">
            <h5 class="card-title">Piano and Keyboards</h5>
            <p class="card-text">Unlock the full spectrum of musical expression with our exquisite pianos and keyboards. From the rich, resonant tones of grand pianos to the versatility of digital keyboards, we have instruments to inspire pianists of all levels. Elevate your compositions and performances with the perfect keyboard instrument.</p>
            <%= link_to "Shop Pianos and Keyboards", pianos_path, class:"btn btn-dark" %>
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <%= image_tag("music_book_product_image.png") %>
        <div class="card-body">
            <h5 class="card-title">Music Books</h5>
            <p class="card-text">Enhance your musical knowledge and skills with our curated selection of music books. Whether you're a beginner seeking guidance or an experienced musician looking to expand your repertoire, our collection includes sheet music, instructional guides, and music theory books. Dive into the world of musical knowledge and refine your craft.</p>
            <%= link_to "Shop Music Books", books_path, class:"btn btn-dark" %>
        </div>
    </div>
</div>


</div>

app/views/products/books.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
<%=render 'layouts/sidenav'%>

   <div>
    <h4 class="mt-3" >Music Books</h4>
            <div class="product-layout mt-4 d-flex justify-content-around">
                <%@products.each do |product|%>
                    <div class="card" style="width: 18rem;">
                        <%= image_tag(product.product_image, class:"card-img-top")%>
                        <div class="card-body">
                            <h5 class="card-title"><%= product.product_name %></h5>
                            <p class="card-text"> <%= product.product_description %> </p>
                            <p class="card-text">R <%= product.product_price %></p>
                            <%= button_to "View Product", class:"btn btn-info"%>
                        </div>
                    </div>
                <% end %>
            </div>
   </div>


</div>

app/views/products/percussion.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
<%=render 'layouts/sidenav'%>

    <div>
        <h4 class="mt-3" >Percussion Instruments</h4>
            <div class="product-layout mt-4 d-flex justify-content-around">
                <%@products.each do |product|%>
                    <div class="card" style="width: 18rem;">
                        <%= image_tag(product.product_image, class:"card-img-top")%>
                        <div class="card-body">
                            <h5 class="card-title"><%= product.product_name %></h5>
                            <p class="card-text"> <%= product.product_description %> </p>
                            <p class="card-text">R <%= product.product_price %></p>
                            <%= button_to "View Product", class:"btn btn-info"%>
                        </div>
                    </div>
                <% end %>
            </div>
    </div>


</div>

app/views/products/pianos.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
<%=render 'layouts/sidenav'%>

    <div>
        <h4 class="mt-3" >Pianos and Keyboards</h4>
            <div class="product-layout mt-4 d-flex justify-content-around">
                <%@products.each do |product|%>
                    <div class="card" style="width: 18rem;">
                        <%= image_tag(product.product_image, class:"card-img-top")%>
                        <div class="card-body">
                            <h5 class="card-title"><%= product.product_name %></h5>
                            <p class="card-text"> <%= product.product_description %> </p>
                            <p class="card-text">R <%= product.product_price %></p>
                            <%= button_to "View Product", class:"btn btn-info"%>
                        </div>
                    </div>
                <% end %>
            </div>
    </div>


</div>

app/views/products/stringed.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
<%=render 'layouts/sidenav'%>

    <div>
    <h4 class="mt-3" >Stringed Instruments</h4>
        <div class="product-layout mt-4 d-flex justify-content-around">
            <%@products.each do |product|%>
                    <div class="card" style="width: 18rem;">
                        <%= image_tag(product.product_image, class:"card-img-top")%>
                        <div class="card-body">
                            <h5 class="card-title"><%= product.product_name %></h5>
                            <p class="card-text"> <%= product.product_description %> </p>
                            <p class="card-text">R <%= product.product_price %></p>
                            <%= button_to "View Product", class:"btn btn-info"%>
                        </div>
                    </div>
            <% end %>
        </div>
        
   </div>

</div>

app/views/products/wind.html.erb
<%= render 'layouts/nav' %> 
<div class="container c-body">
<%=render 'layouts/sidenav'%>

    <div>
        <h4 class="mt-3" >Wind Instruments</h4>
            <div class="product-layout mt-4 d-flex justify-content-around">
                <%@products.each do |product|%>
                    <div class="card" style="width: 18rem;">
                        <%= image_tag(product.product_image, class:"card-img-top")%>
                        <div class="card-body">
                            <h5 class="card-title"><%= product.product_name %></h5>
                            <p class="card-text"> <%= product.product_description %> </p>
                            <p class="card-text">R <%= product.product_price %></p>
                            <%= button_to "View Product", class:"btn btn-info"%>
                        </div>
                    </div>
                <% end %>
            </div>
    </div>


</div>